const { Schema, model } = require("mongoose");

const couponSchema = new Schema(
  {
    name: { type: String, required: true, trim: true },
    code: {
      type: String,
      required: true,
      unique: true,
      uppercase: true,
      trim: true,
    },
    discountType: {
      type: String,
      enum: ["percentage", "fixed"],
      required: true,
    },
    discountValue: {
      type: Number,
      required: true,
      min: 0,
    },
    expiresAt: { type: Date, default: null }, // null = never expires
    isActive: { type: Boolean, default: true },

    // Stripe references
    stripeCouponId: { type: String, default: null },
    stripePromotionCodeId: { type: String, default: null },

    // ── Retention coupon metadata ────────────────────────────────────────────
    // Set to true for coupons auto-generated by the retention/cancel flow
    isRetentionCoupon: { type: Boolean, default: false },

    // The user who triggered this coupon generation (1 retention coupon per user lifetime)
    generatedForUserId: { type: Schema.Types.ObjectId, ref: "User", default: null },

    // Usage limits
    maxUses: { type: Number, default: null }, // null = unlimited; 1 for retention coupons
    timesUsed: { type: Number, default: 0 },

    // Audit trail of every time this coupon was applied
    usageHistory: {
      type: [
        {
          userId: { type: Schema.Types.ObjectId, ref: "User" },
          usedAt: { type: Date, default: Date.now },
          invoiceId: { type: String, default: null },
          _id: false,
        },
      ],
      default: [],
    },

    // Soft delete
    isDeleted: { type: Boolean, default: false },
    deletedAt: { type: Date, default: null },
  },
  { timestamps: true }
);

couponSchema.index({ code: 1, isDeleted: 1 });
couponSchema.index({ isActive: 1, expiresAt: 1 });

const Coupon = model("Coupon", couponSchema);
module.exports = Coupon;
